export const MILLISECONDS_OF_A_SECOND = 1000
export const MILLISECONDS_OF_A_MINUTE = MILLISECONDS_OF_A_SECOND * 60
export const MILLISECONDS_OF_A_HOUR = MILLISECONDS_OF_A_MINUTE * 60
export const MILLISECONDS_OF_A_DAY = MILLISECONDS_OF_A_HOUR * 24

export enum IntervalOption {
    HOURS = 'HOURS',
    MINUTES = 'MINUTES',
    SECONDS = 'SECONDS',
    MILLISECONDS = 'MILLISECONDS',
}